"""
Django settings for abstra_lab project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-0!1@d6d)d)i^ue*7$*3pr5wu2wp=7psa2*izdhqakdn+bx7gl)',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        '127.0.0.1,localhost,192.168.0.166',
    ).split(',')
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'telemetry',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'abstra_lab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.auth_flags',
                'core.context_processors.role_flags',
                'core.context_processors.site_nav',
                'core.context_processors.seo_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'abstra_lab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_postgres_host = os.environ.get('POSTGRES_HOST', '').strip()
if _postgres_host:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'astra'),
            'USER': os.environ.get('POSTGRES_USER', 'astra'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': _postgres_host,
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_IMAGES_ROOT = MEDIA_ROOT / 'images'

# Club reference files live outside the Django app tree (not mixed with code).
REPO_ROOT = BASE_DIR.parent
REFERENCE_ROOT = REPO_ROOT / 'references'
REFERENCE_UPLOAD_ROOT = REFERENCE_ROOT / 'uploads'

# SeaweedFS S3-compatible object storage (replaces local/MinIO for uploads).
SEAWEEDFS_S3_ENDPOINT_URL = os.environ.get('SEAWEEDFS_S3_ENDPOINT_URL', '').strip()
USE_SEAWEEDFS = bool(SEAWEEDFS_S3_ENDPOINT_URL)
SEAWEEDFS_S3_ACCESS_KEY = os.environ.get('SEAWEEDFS_S3_ACCESS_KEY', '')
SEAWEEDFS_S3_SECRET_KEY = os.environ.get('SEAWEEDFS_S3_SECRET_KEY', '')
SEAWEEDFS_S3_BUCKET_NAME = os.environ.get('SEAWEEDFS_S3_BUCKET_NAME', 'astra-lab')
SEAWEEDFS_S3_REGION_NAME = os.environ.get('SEAWEEDFS_S3_REGION_NAME', 'us-east-1')
SEAWEEDFS_S3_USE_SSL = os.environ.get('SEAWEEDFS_S3_USE_SSL', '1') == '1'
SEAWEEDFS_S3_VERIFY_SSL = os.environ.get('SEAWEEDFS_S3_VERIFY_SSL', '1') == '1'


def _seaweedfs_storage_options(location):
    return {
        'bucket_name': SEAWEEDFS_S3_BUCKET_NAME,
        'access_key': SEAWEEDFS_S3_ACCESS_KEY,
        'secret_key': SEAWEEDFS_S3_SECRET_KEY,
        'endpoint_url': SEAWEEDFS_S3_ENDPOINT_URL,
        'region_name': SEAWEEDFS_S3_REGION_NAME,
        'addressing_style': 'path',
        'signature_version': 's3v4',
        'use_ssl': SEAWEEDFS_S3_USE_SSL,
        'verify': SEAWEEDFS_S3_VERIFY_SSL,
        'file_overwrite': False,
        'querystring_auth': True,
        'location': location,
    }


_staticfiles_backend = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
    if os.environ.get('DJANGO_STATICFILES_MANIFEST', '0') == '1'
    else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': MEDIA_ROOT,
            'base_url': MEDIA_URL,
        },
    },
    'staticfiles': {
        'BACKEND': _staticfiles_backend,
    },
}

if USE_SEAWEEDFS:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': _seaweedfs_storage_options('media'),
        },
        'staticfiles': {
            'BACKEND': _staticfiles_backend,
        },
        'library': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': _seaweedfs_storage_options('library'),
        },
    }

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_ADAPTER = 'core.adapters.MemberAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'core.adapters.MemberSocialAccountAdapter'
ACCOUNT_FORMS = {
    'login': 'core.forms.MemberLoginForm',
    'signup': 'core.forms.MemberSignupForm',
}
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_ON_SIGNUP = False
ACCOUNT_LOGOUT_ON_GET = False
ACCOUNT_SIGNUP_REDIRECT_URL = '/accounts/pending/'
ACCOUNT_LOGIN_REDIRECT_URL = '/dashboard/'

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_OAUTH_ENABLED = bool(GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET)

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': '',
        },
    },
}

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

TELEMETRY_INGEST_TOKEN = os.environ.get(
    'TELEMETRY_INGEST_TOKEN',
    'dev-telemetry-token' if DEBUG else '',
)
