# Generated by Django 6.0.5 on 2026-06-05 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('vehicle', models.CharField(default='Pioneer', max_length=120)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('complete', 'Complete'), ('aborted', 'Aborted')], default='planned', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ground_station', models.CharField(blank=True, max_length=120)),
                ('packet_kind', models.CharField(default='telemetry', max_length=64)),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True)),
                ('rocket_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('velocity_mps', models.FloatField(blank=True, null=True)),
                ('acceleration_mps2', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('battery_v', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('pressure_pa', models.FloatField(blank=True, null=True)),
                ('rssi_dbm', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frames', to='telemetry.flightsession')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='telemetry_t_receive_b1efc4_idx'), models.Index(fields=['ground_station', '-received_at'], name='telemetry_t_ground__80954f_idx')],
            },
        ),
    ]
